cd .\out\build\x64-Clang-Debug\Mw05Recomp

# Minimal, stable profile: disable aggressive VD ISR forcing and ACK hacks
$env:MW05_DEBUG_PROFILE=0
$env:MW05_LOG_DBG_BREAK=0
$env:MW05_FILE_LOG=1
$env:MW05_HOST_TRACE_IMPORTS=1
$env:MW05_HOST_TRACE_HOSTOPS=1
$env:MW05_PM4_SWAP_PRESENT=1
$env:MW05_PRESENT_HEARTBEAT_MS=250
$env:MW05_FORCE_PRESENT=0
$env:MW05_VBLANK_CB=0
$env:MW05_DEFAULT_VD_ISR=0
$env:MW05_REGISTER_DEFAULT_VD_ISR=0
$env:MW05_FORCE_VD_ISR=0
$env:MW05_FORCE_ACK_WAIT=0
$env:MW05_ZERO_EVENT_PTR_AFTER_ACK=0
$env:MW05_ZERO_EVENT_STATUS_AFTER_ACK=0
$env:MW05_HOST_ISR_TICK_SYSID=0
$env:MW05_HOST_ISR_ACK_EVENT=0
$env:MW05_HOST_ISR_TRACE_LAST_WAIT=0
$env:MW05_HOST_ISR_FORCE_SIGNAL_LAST_WAIT=0
$env:MW05_HOST_ISR_SIGNAL_VD_EVENT=0
$env:MW05_HOST_ISR_NOTIFY_SRC_SEQ=""
$env:MW05_HOST_ISR_RB_STEP=0

# Optional verbose file I/O and loader traces (keep or remove as needed)
$env:MW05_STREAM_BRIDGE=1
$env:MW05_TRACE_LOADER_ARGS=1
$env:MW05_FILE_LOG=1

.\Mw05Recomp.exe

