## Need for Speed: Most Wanted (2005) – Xbox 360
## XenonRecomp title profile (config) for static recompilation
## MINIMAL VERSION - Following UnleashedRecomp's approach

[main]
# XEX input/output paths are relative to this config file location
file_path = "../private/default.xex"
# Optional patch file (.xexp) if present
# patch_file_path = "../private/default.xexp"
patched_file_path = "../private/default_patched.xex"
out_directory_path = "../ppc"
switch_table_file_path = "MW05_switch_tables.toml"

# Register allocation heuristics
# Following UnleashedRecomp's aggressive optimization settings
skip_lr = true
skip_msr = true
ctr_as_local = true
xer_as_local = true
reserved_as_local = true
cr_as_local = true
non_argument_as_local = true
non_volatile_as_local = true

# Prolog/epilog helpers (MW'05 addresses)
restgprlr_14_address = 0x826BDD80
savegprlr_14_address = 0x826BDD30
restfpr_14_address   = 0x826BED3C
savefpr_14_address   = 0x826BECF0
restvmx_14_address   = 0x826BEA58
savevmx_14_address   = 0x826BE7C0
restvmx_64_address   = 0x826BEAEC
savevmx_64_address   = 0x826BE854

# longjmp_address = 0x00000000
# setjmp_address = 0x00000000

# These functions do not exist in .pdata and do
# not analyze properly due to having jump tables
# NOTE: This list should be populated from actual recompiler errors
# Currently empty - let the recompiler handle everything automatically
functions = [
]

# Invalid instructions (if any are discovered during testing)
# invalid_instructions = [
#     { data = 0x00000000, size = 4 }, # Padding
# ]

# Mid-ASM hooks (if needed for game-specific fixes)
# [[midasm_hook]]
# name = "ExampleMidAsmHook"
# address = 0x82000000
# registers = ["r3"]
