# MW'05 (Xbox 360) — XenonRecomp main config
# Update the save/restore helper addresses at the bottom before running a full recompile.

[main]
# Your XEX (uses forward slashes so TOML doesn't need escaping)
file_path = "../private/default.xex"
# patch_file_path = "../private/default.xexp"
patched_file_path = "../private/default_patched.xex"
out_directory_path = "../ppc"
switch_table_file_path = "SWA_switch_tables.toml"

# Leave these conservative until you have a clean pass
skip_lr = false
skip_msr = false
ctr_as_local = false
xer_as_local = false
reserved_as_local = false
cr_as_local = false
non_argument_as_local = false
non_volatile_as_local = false

restgprlr_14_address = 0x826BDD80
savegprlr_14_address = 0x826BDD30
restfpr_14_address   = 0x826BED3C
savefpr_14_address   = 0x826BECF0
restvmx_14_address   = 0x826BEA58
savevmx_14_address   = 0x826BE7C0
restvmx_64_address   = 0x826BEAEC
savevmx_64_address   = 0x826BE854

# longjmp_address = 0x00000000
# setjmp_address = 0x00000000

# These functions do not exist in .pdata and do
# not analyze properly due to having jump tables
# functions = []

# invalid_instructions = []
