@echo off
REM This batch file runs Mw05Recomp.exe with all environment variables set
REM It's called from run_with_debug.ps1 to ensure environment variables are inherited

REM Enable debug profile to apply default environment variables
set MW05_DEBUG_PROFILE=1

REM Set all environment variables from run_with_debug.ps1
set MW05_HOST_TRACE_FILE=mw05_host_trace.log
set MW05_BREAK_82813514=0
set MW05_FAKE_ALLOC_SYSBUF=1
set MW05_UNBLOCK_MAIN=0
set MW05_TRACE_KERNEL=1
set MW05_HOST_TRACE_IMPORTS=1
set MW05_HOST_TRACE_HOSTOPS=1
set MW05_TRACE_HEAP=1
set MW05_BREAK_SLEEP_LOOP=1
set MW05_BREAK_SLEEP_AFTER=5

set MW05_VBLANK_VDSWAP=0
set MW05_KICK_VIDEO=0
set MW05_VDSWAP_NOTIFY=0
set MW05_FAST_BOOT=0
set MW05_FAST_RET=0
set MW05_FORCE_VD_INIT=1

set MW05_TRACE_INDIRECT=0
set MW05_TITLE_STATE_TRACE=1
set MW05_BREAK_WAIT_LOOP=0
set MW05_FORCE_VIDEO_THREAD=0
set MW05_FORCE_VIDEO_THREAD_TICK=0
set MW05_DEFAULT_VD_ISR=0
set MW05_REGISTER_DEFAULT_VD_ISR=0
set MW05_PULSE_VD_ON_SLEEP=0
set MW05_PRESENT_HEARTBEAT_MS=0

set MW05_STREAM_BRIDGE=1
set MW05_STREAM_FALLBACK_BOOT=1
set MW05_STREAM_ACK_NO_PATH=0
set MW05_LOOP_TRY_PM4_PRE=0
set MW05_LOOP_TRY_PM4_POST=0
set MW05_INNER_TRY_PM4=0
set MW05_FORCE_GFX_NOTIFY_CB=1
set MW05_FORCE_GFX_NOTIFY_CB_CTX=0x40007180
set MW05_FORCE_GFX_NOTIFY_CB_DELAY_TICKS=350
set MW05_VD_ISR_SWAP_PARAMS=0

set MW05_FORCE_PRESENT=1
set MW05_FORCE_PRESENT_BG=1
set MW05_FORCE_PRESENT_WRAPPER_DELAY_TICKS=0
set MW05_FORCE_PRESENT_WRAPPER_ONCE=1
set MW05_FORCE_PRESENT_EVERY_ZERO=1
set MW05_FORCE_PRESENT_ON_ZERO=1
set MW05_FORCE_PRESENT_ON_FIRST_ZERO=1

set MW05_SCHED_R3_EA=0x00260370
set MW05_FPW_KICK_PM4=1

REM Force-create the render threads that issue draw commands
set MW05_FORCE_RENDER_THREADS=1

REM Signal the VD interrupt event to wake up the render thread
set MW05_HOST_ISR_SIGNAL_VD_EVENT=1
set MW05_PULSE_VD_EVENT_ON_SLEEP=1

REM Enable PM4 state application
set MW05_PM4_APPLY_STATE=1

REM Force the flag at r31+10434 that gates present calls
set MW05_FORCE_PRESENT_FLAG=1

REM CRITICAL: Enable present callback pointer workaround
set MW05_SET_PRESENT_CB=1

REM Debug: Verify environment variables are set
echo [CMD-DEBUG] MW05_UNBLOCK_MAIN=%MW05_UNBLOCK_MAIN%
echo [CMD-DEBUG] MW05_STREAM_BRIDGE=%MW05_STREAM_BRIDGE%
echo [CMD-DEBUG] MW05_HOST_TRACE_FILE=%MW05_HOST_TRACE_FILE%
echo [CMD-DEBUG] MW05_SET_PRESENT_CB=%MW05_SET_PRESENT_CB%

cd /d "%~dp0..\out\build\x64-Clang-Debug\Mw05Recomp"
Mw05Recomp.exe 2> debug_stderr.txt

