cmake_minimum_required(VERSION 3.20)

# Determine directories
get_filename_component(SCRIPT_DIR "${CMAKE_SCRIPT_MODE_FILE}" DIRECTORY)
get_filename_component(LIB_DIR "${SCRIPT_DIR}/.." ABSOLUTE)
set(PPC_DIR "${LIB_DIR}/ppc")
set(OUT_FILE "${PPC_DIR}/generated_sources.cmake")

file(GLOB _ppc_sources RELATIVE "${LIB_DIR}" "${PPC_DIR}/ppc_recomp.*.cpp")
list(SORT _ppc_sources)

file(WRITE "${OUT_FILE}" "# Auto-generated by gen_ppc_list.cmake\n")
file(APPEND "${OUT_FILE}" "set(MW05_RECOMP_PPC_RECOMPILED_SOURCES\n")
foreach(s IN LISTS _ppc_sources)
    file(APPEND "${OUT_FILE}" "    \"${LIB_DIR}/${s}\"\n")
endforeach()
file(APPEND "${OUT_FILE}" ")\n")

message(STATUS "Wrote PPC source list: ${OUT_FILE} (${_ppc_sources})")

